### ISSUE TITLE
Checklist before final benchmark can run

### ISSUE THREAD

**Issue by jemus42** [slds-lmu/paper_2023_survival_benchmark#3]
From proba_benchmark created by [jemus42](https://github.com/jemus42): RaphaelS1/proba_benchmark#58  

- [x] Finalize learner inclusion
   - Removing DL
   - Not adding anything new 
- [x] Finalize task inclusion
- [x] Related: Finalize preprocessing (see also #55 #56)
- [x] Decide on tuning budget (see here https://github.com/RaphaelS1/proba_benchmark/blob/42f763c76c8eb1ef3a8af50db942009a0a3a5a64/batchmark.R#L91 and here https://github.com/RaphaelS1/proba_benchmark/blob/42f763c76c8eb1ef3a8af50db942009a0a3a5a64/settings.R#L15-L16 )
- [X] Pretest for runtime and memory usage estimation
    - Waiting for https://github.com/xoopR/distr6/pull/296 and new ranger CRAN release will help 
- [X] Do we include `glmnet` with its own distr estimate?
    - (Yes, this happens automatically if we update extralearners and glmnet appropriately) 	
- [x] Settle on measures for tuning (evaluation measures could be adapted even after benchmark is run)
    --> Decided to run on harrell as primary tuning measure, RCLL as secondary measure
- [x] Access to wyoming cluster 
- [x] https://github.com/mlr-org/mlr3extralearners/issues/327
- [X]  https://github.com/mlr-org/mlr3extralearners/pull/330
	- [X] Presumably requires setting `discrete = TRUE` for `surv.parametric` 
- [x] https://github.com/mlr-org/mlr3extralearners/pull/332
- [X] Split surv.parametric in ph/aft forms
- [x] Breslow: https://github.com/mlr-org/mlr3proba/pull/338
- [x] https://github.com/mlr-org/mlr3proba/issues/344 (causes fallback to kick in, invalidating results)
- [X] Split xgboost in cox + aft
    - PR not required: (https://github.com/mlr-org/mlr3extralearners/pull/333)
